
import os
import sys
import json
import numpy as np

from sana_geo import Polygon

def get_fullpath(f):
    return os.path.abspath(os.path.expanduser(f))

def create_directory(f):
    if not os.path.exists(os.path.dirname(f)):
        os.makedirs(os.path.dirname(f))

# sometimes the json files generated by qupath 7 unreadable bytes
# this function checks if they exist, and removes them from the file
def fix_qupath_annotations(ifname):
    fp = open(ifname, 'rb')
    header = fp.read(7)
    if bytes([header[0]]) != bytes([91]):
        data = fp.read()
        fp.close()
        fp = open(ifname, 'wb')
        fp.write(data)
        fp.close()

def read_qupath_annotations(ifname, mpp, ds):

    # remove unnecessary bytes at beginning of file if they exist
    fix_qupath_annotations(ifname)

    # prepare the input file
    fp = open(ifname, 'r')

    # load the data
    data = json.loads(fp.read())

    # TODO: handle the multipolygon better than this, why is there sometimes 2 sets of coords
    annotations = []
    for annotation in data:
        geo = annotation['geometry']
        if geo['type'] == 'MultiPolygon':
            coords_list = geo['coordinates']
        elif geo['type'] == 'Polygon':
            coords_list = [geo['coordinates']]
        for coords in coords_list:
            x = np.array([float(c[0]) for c in coords[0]])
            y = np.array([float(c[1]) for c in coords[0]])
            poly = Polygon(x, y, mpp, ds, is_micron=False)
            annotations.append(poly)
    return annotations

#
# end of file
